#!/bin/bash
#SBATCH -A mp309
#SBATCH -C gpu
#SBATCH -q regular
#SBATCH -t 0:01:00
#SBATCH -N 8
#SBATCH --ntasks-per-node=1
#SBATCH -c 128
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=none

srun ./mpi_rsa
