#!/bin/bash
#SBATCH -A mp309
#SBATCH -C gpu
#SBATCH -q regular
#SBATCH -t 0:10:00
#SBATCH -N 2
#SBATCH --ntasks-per-node=2
#SBATCH -c 64
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=none

srun ./mpi_rsa
